name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey there! Thanks for opening an issue and contributing!! Incase of any queries, join our discord server here : https://discord.gg/YfwfA4JbdW'
        pr-message: 'Hey there! Thanks for opening your pr and contributing!! Incase of any queries, join our discord server here : https://discord.gg/YfwfA4JbdW'
